version: "3.9"
services:
  db:
    image: postgres:16
    container_name: sls_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: securelogin
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d securelogin"]
      interval: 5s
      timeout: 3s
      retries: 10
volumes:
  db:
